# Variables
# Special rules and targets
.PHONY: all build clean help
# Rules and targets
all: build
build:
	@cd src && $(MAKE)
	@cp -f src/sudoku .
clean:
	@cd src && $(MAKE) clean
	@rm -f sudoku
help:
	@echo -e "Usage:"
	@echo -e " make [all]\t\tBuild"
	@echo -e " make build\t\tBuild the software"
	@echo -e " make check\t\tRun all the tests"
	@echo -e " make clean\t\tRemove all files generated by make"
	@echo -e " make help\t\tDisplay this help"
